[project]
name = "pdfplumber-bank-ru"
version = "0.1.0"

authors = [{name = "Anna Loginova"}]
description = "Convert accocunt statemenet to pandas DataFrame"
readme = "README.md"

requires-python = ">=3.11"
dependencies = [
    "numpy>=2.0.0,<3.0.0",
    "pandas>=2.0.0,<4.0.0",
    "pdfplumber>=0.11.10,<1.0.0",
]

[dependency-groups]
lint = [
    "ruff>=0.16.5",
]
test = [
    "pytest>=9.1.1",
    "tox>=4.61.2",
]


[tool.ruff]
line-length = 127
indent-width = 4

[tool.ruff.lint]
ignore = [
    "UP006", "UP007", "UP035", "UP045",
    "I001",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.tox]
requires = ["tox>=4.19"]
env_list = ["3.14", "3.13", "3.12", "3.11"]

[tool.tox.env_run_base]
description = "Run test under {base_python}"
allowlist_externals = [
    "pytest",
]
commands = [["pytest"]]
